### PR TITLE
#78 Added functionality for accessing the current ModelInstanceRepository implementation outside of the GenerationContext

### LINKED ISSUE #78: Retrieval mechanisms for the active ModelInstanceRepository inhibit extension patterns.
Currently, the only mechanism to retrieve the configured `ModelInstanceRepository` implementation instance, and thus to interrogate the underlying schemas informing generation, is to use this static method provided in the `ModelInstanceRepositoryManager` class: 

```
    public static <V> V getMetamodelRepository(Class<V> type) {
        Map<String, Object> instanceMap = threadBoundInstance.get();
        return type.cast(instanceMap.get(type.toString()));
    }
```

Suppose a fermenter-based project `Project_A` provides their own `ModelInstanceRepository` implementation, `MIR_A`.  Within the project's generators, they may be forced to include code such as the following:

```
MIR_A metamodelRepository = ModelInstanceRepositoryManager
                .getMetamodelRepository(MIR_A.class);
```

This will work fine for this initial project.  However, if another project `Project_B` is created to extend `Project_A`, with its own `ModelInstanceRepository` implementation `MIR_B extends MIR_A`, then existing calls of the above snippet will fail with null pointer exceptions.  This is due to the naive string-name lookup method found in the `getMetamodelRepository` method above.  Extension patterns are thus inhibited.

### PR DESCRIPTION
**Pull request by carter-cundiff**
Some metamodel classes (ex: [RecordFieldTypeElement.java](https://github.com/boozallen/aissemble/blob/dev/foundation/foundation-mda/src/main/java/com/boozallen/aiops/mda/metamodel/element/RecordFieldTypeElement.java)) need access to the current `ModelInstanceRepository` before the `GenerationContext` has been created. 

Given `MIR_A implements ModelInstanceRepository` and `MIR_B extends MIR_A`, the old way fails when the implementation class for an execution is `MIR_B` but the upstream fermenter project still contains references to `MIR_A`. The new way allows for those references to remain intact while allowing others to extend their project.

Old way would return a NPE as `MIR_A.class` doesn't exist in the map, only `MIR_B.class`:
```
MIR_A modelRepository = ModelInstanceRepositoryManager.getMetamodelRepository(MIR_A.class);
```

### CODE REVIEW

File: fermenter-mda/src/main/java/org/technologybrewery/fermenter/mda/metamodel/ModelInstanceRepositoryManager.java [hunk 1]
```diff
@@ -37,6 +37,25 @@ public static <V> V getMetamodelRepository(Class<V> type) {
...
     }
 
+    /**
+     * Returns the stored repository for a given class including it's subclasses (if present).
+     * 
+     * @param type
+     *            class to lookup
+     * @return instance of that class
+     */
+    public static <V> V getMetamodelRepositoryWithExtensions(Class<V> type) {
```
Comment (epwilkins) [inline fermenter-mda/src/main/java/org/technologybrewery/fermenter/mda/metamodel/ModelInstanceRepositoryManager.java]: S: This approach feels like it leaves a lot of room for ambiguity about what you're going to get. If you have multiple repositories that extend some common class, and then call this method with that common class, you arbitrarily get what comes first.

I propose we overload `setRepository` with a version that takes the repository and the class to register it as. So you'd call something like `setRepository(BaseRepo.class, new MyExtensionRepo())`.  Then on lookup, it's completely unambiguous. `BaseRepo` should always return `MyExtensionRepo` and only `MyExtensionRepo`. Of course it's still possible that the method be called multiple times with the same key, but that's just the nature of lookup tables/maps I think.

Comment (epwilkins) [reply fermenter-mda/src/main/java/org/technologybrewery/fermenter/mda/metamodel/ModelInstanceRepositoryManager.java]: This also has the benefit of not forcing all implementers to change their calls of `getMetamodelInstanceRepository` with `getMetamodelInstanceRepositoryWithExtension`.

Comment (carter-cundiff) [reply fermenter-mda/src/main/java/org/technologybrewery/fermenter/mda/metamodel/ModelInstanceRepositoryManager.java]: `setRepository()` is called as part of `fermenter-mda/src/main/java/org/technologybrewery/fermenter/mda/GenerateSourcesHelper.java` so it has no way of knowing the base class and extension class as it only has access to `metadataRepositoryImpl`.

Comment (carter-cundiff) [reply fermenter-mda/src/main/java/org/technologybrewery/fermenter/mda/metamodel/ModelInstanceRepositoryManager.java]: We could interrogate the superclass from the current instance but I think that might break as more layers are added. Need to look into it more.

Comment (carter-cundiff) [reply fermenter-mda/src/main/java/org/technologybrewery/fermenter/mda/metamodel/ModelInstanceRepositoryManager.java]: Given `MIR_A implements AbstractModelInstanceRepository`, `MIR_B extends MIR_A`, and `MIR_C extends MIR_B`.

When we're executing with the `MIR_C` repository as our current implementation, we would write:
```
setRepository(MIR_B.class, MIR_C)
```

This would still cause breakage in the `MIR_A` repository on the calls:
```
getMetamodelRepository(MIR_A.class)
```

Unless we want to continue interrogating the given impl class until we hit `AbstractModelInstanceRepository`. Then we would need multiple writes to the set repository for each layer:
```
setRepository(MIR_C.class, MIR_C)
setRepository(MIR_B.class, MIR_C)
setRepository(MIR_A.class, MIR_C)
```

This would allow all calls to get the same `MIR_C` instance:
```
getMetamodelRepository(MIR_A.class) -> MIR_C
getMetamodelRepository(MIR_B.class) -> MIR_C
getMetamodelRepository(MIR_C.class) -> MIR_C
```

Comment (epwilkins) [reply fermenter-mda/src/main/java/org/technologybrewery/fermenter/mda/metamodel/ModelInstanceRepositoryManager.java]: I think from a usage perspective you're telling Fermenter what impl class should be used for a given repository type. I don't think it's a huge deal that you'd have to set it explicitly at multiple levels, because I don't think that would be the correct solution in 99% of cases.

If I register `MIR_B` as the impl for `MIR_A`, I should still write my consuming code at the `MIR_A` level, even in the source that's "aware" of the B impl. And so if B were then extended with C, again it's just replacing the impl of A and all code should be written against A.

We _could_ enforce something around it being an interface if that would feel more natural. That would call out that there is a single interface being programmed _against_ and the impl is decided/provided at runtime. My only concern with requiring an interface would be old code. We'd either need old code to be migrated to be interface-driven, or we'd need to allow both interface-driven and concrete class which seems like it could lead to a lot of edge cases/ambiguity.

Comment (carter-cundiff) [reply fermenter-mda/src/main/java/org/technologybrewery/fermenter/mda/metamodel/ModelInstanceRepositoryManager.java]: So if I follow correctly,  you're saying that even in the `MIR_B` and `MIR_C` repos, they should still really only be using:
```
getMetamodelRepository(MIR_A.class)
```

Given we want to preserve the existing `setRepository()` rather than make it an interface and introduce a breaking change, we would still need to interrogate the impl until we find the base class. If we're doing that interrogation I don't see any harm in adding all the intermediate classes along the way:
```
    public static void setRepository(ModelInstanceRepository repository) {
        Map<String, Object> instanceMap = threadBoundInstance.get();

        instanceMap.put(repository.getClass().toString(), repository);
        Class<?> repositorySuperClass = repository.getClass().getSuperclass();

        while (!repositorySuperClass.getName().equals("org.technologybrewery.fermenter.mda.metamodel.AbstractModelInstanceRepository")) {
            instanceMap.put(repositorySuperClass.toString(), repository);
            repositorySuperClass = repositorySuperClass.getSuperclass();
        }
    }
```

File: fermenter-mda/src/main/java/org/technologybrewery/fermenter/mda/metamodel/ModelInstanceRepositoryManager.java [hunk 2]
```diff
@@ -10,19 +10,43 @@ public final class ModelInstanceRepositoryManager {
...
+    private static final String ABSTRACT_MODEL_INSTANCE_REPOSITORY_CLASS_NAME = 
+                                "org.technologybrewery.fermenter.mda.metamodel.AbstractModelInstanceRepository";
+
     private ModelInstanceRepositoryManager() {
         // prevent private instantiation of all static class
     }
 
     /**
-     * Adds a repository. Only one repository of each type will be kept.
+     * Adds a repository and creates references to it for the current impl class and any super
```
Comment (epwilkins) [inline fermenter-mda/src/main/java/org/technologybrewery/fermenter/mda/metamodel/ModelInstanceRepositoryManager.java]: A:
```suggestion
     * Sets a repository as the repository implementation for its own class and any super 
```

**Review by epwilkins — APPROVED** [review]
