### PR TITLE
FER-78: Exposed the current ModelInstanceRepository implementation th…

### LINKED ISSUE #78: Retrieval mechanisms for the active ModelInstanceRepository inhibit extension patterns.
Currently, the only mechanism to retrieve the configured `ModelInstanceRepository` implementation instance, and thus to interrogate the underlying schemas informing generation, is to use this static method provided in the `ModelInstanceRepositoryManager` class: 

```
    public static <V> V getMetamodelRepository(Class<V> type) {
        Map<String, Object> instanceMap = threadBoundInstance.get();
        return type.cast(instanceMap.get(type.toString()));
    }
```

Suppose a fermenter-based project `Project_A` provides their own `ModelInstanceRepository` implementation, `MIR_A`.  Within the project's generators, they may be forced to include code such as the following:

```
MIR_A metamodelRepository = ModelInstanceRepositoryManager
                .getMetamodelRepository(MIR_A.class);
```

This will work fine for this initial project.  However, if another project `Project_B` is created to extend `Project_A`, with its own `ModelInstanceRepository` implementation `MIR_B extends MIR_A`, then existing calls of the above snippet will fail with null pointer exceptions.  This is due to the naive string-name lookup method found in the `getMetamodelRepository` method above.  Extension patterns are thus inhibited.

### PR DESCRIPTION
**Pull request by peter-mcclonski**
…rough the GenerationContext.

### CODE REVIEW

File: fermenter-mda/src/main/java/org/technologybrewery/fermenter/mda/GenerateSourcesMojo.java [hunk 1]
```diff
@@ -249,6 +247,27 @@ private void setup() throws MojoExecutionException {
...
+     * Helper method to retrieve and validate the ModelInstanceRepository implementation class.
+     *
+     * @throws MalformedURLException
+     * @throws ClassNotFoundException
+     * @throws InvocationTargetException
+     * @throws NoSuchMethodException
+     * @throws InstantiationException
+     * @throws IllegalAccessException
+     */
+    protected void buildModelInstanceRepository() throws MalformedURLException, ClassNotFoundException,
```
Comment (peter-mcclonski) [inline fermenter-mda/src/main/java/org/technologybrewery/fermenter/mda/GenerateSourcesMojo.java:260]: I: Extracted out this logic largely just to help with testing.

**Review by d-ryan-ashcraft — APPROVED** [review]
LGTM - thanks!
